### ISSUE TITLE
Syntax error on `Simput -p`: unexpected token `(`

### ISSUE THREAD

**Issue by daniellivingston** [Kitware/simput#59]
On a fresh `npm install -g simput` install, I get the following traceback:

```
$ Simput -p
/usr/local/lib/node_modules/simput/node_modules/serve-handler/src/index.js:178
const getHeaders = async (customHeaders = [], current, absolutePath, stats) => {
                         ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/simput/src/cli/simput-cli.js:72:19)
```

### System:

```
$ npm -v
6.11.3

$ node -v
v6.11.4

$ uname -rsm
Darwin 18.7.0 x86_64
```

**Comment by daniellivingston** [comment]
## Solution:

My install of Node.js was out of date. Updating to the latest version resolved the issue.

```
$ brew install n
$ sudo -E n latest
$ node -v
v12.10.0
```

**Comment by jourdain** [comment]
You were faster than me catching up on email ;-)

I'm glad you figure it out.
